default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: leagueanalytics_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: leagueanalytics_test

production:
  <<: *default
  database: leagueanalytics_production
  username: leagueanalytics
  password: <%= ENV['LEAGUEANALYTICS_DATABASE_PASSWORD'] %>
